micronaut:
  application:
    name: ios_test

ios:
  appiumServerUrl: ${http://0.0.0.0:4723/}
  platformName: iOS
  platformVersion: 16.4
  deviceName: iPhone 12
  automationName: XCUITest
  app:
    path: /Users/akshat.tambe/Downloads/UIKitCatalog.app.zip
